services:
  - type: web
    name: friendzy-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://friendzy_user:KOT3ITnsydy0sTHi@friendzy.wuosvub.mongodb.net/friendzy?retryWrites=true&w=majority&appName=Friendzy
      - key: JWT_KEY
        value: "(^(&()^(&^*&^@()&@!LNASLBKJASBN!123123123@#@@#)))"
      - key: ORIGIN
        value: https://friendzy-web.onrender.com

  - type: web
    name: friendzy-web
    env: static
    plan: free
    rootDir: React_node_chat_app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://friendzy-api.onrender.com